// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrcpKhzj0x40r-cqT213TVABYl96kdHa0',
    appId: '1:286497040331:web:3f1b76dededfb22244384e',
    messagingSenderId: '286497040331',
    projectId: 'chatprojectapp-c76f8',
    authDomain: 'chatprojectapp-c76f8.firebaseapp.com',
    storageBucket: 'chatprojectapp-c76f8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OyO7I48rFG95DPck-nwSw35qegVjXq0',
    appId: '1:286497040331:android:30315a6981118f2044384e',
    messagingSenderId: '286497040331',
    projectId: 'chatprojectapp-c76f8',
    storageBucket: 'chatprojectapp-c76f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxCMJ4kNEkn39FDI5cYdaBIxMeGKybMM',
    appId: '1:286497040331:ios:ecb8313739fd41fa44384e',
    messagingSenderId: '286497040331',
    projectId: 'chatprojectapp-c76f8',
    storageBucket: 'chatprojectapp-c76f8.appspot.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
